### PR TITLE
Fix a typo in screedRecord

### PR DESCRIPTION
**Pull request by kdmurray91**
This is a trivial patch. Was reading the code and noticed a typo in a try: except: block.

### CODE REVIEW

**Comment by kdmurray91** [comment]
- [x] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by kdmurray91** [comment]
Got a test failure, but that exists in master.

```
............................................................................S....................E.E..
======================================================================
ERROR: screed.tests.test_streaming.test_stream_fa_gz
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/prog/.virtualenvs/khmer-dev/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/kevin/prog/bio/forks/screed/screed/tests/test_streaming.py", line 64, in test_stream_fa_gz
    streamer(os.path.join(os.path.dirname(__file__), 'test.fa.gz'))
  File "/home/kevin/prog/bio/forks/screed/screed/tests/test_streaming.py", line 51, in streamer
    raise exception[0]
ValueError: gziped data not streamable, pipe through zcat                              first

======================================================================
ERROR: screed.tests.test_streaming.test_stream_fq_gz
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/prog/.virtualenvs/khmer-dev/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/kevin/prog/bio/forks/screed/screed/tests/test_streaming.py", line 77, in test_stream_fq_gz
    streamer(os.path.join(os.path.dirname(__file__), 'test.fastq.gz'))
  File "/home/kevin/prog/bio/forks/screed/screed/tests/test_streaming.py", line 51, in streamer
    raise exception[0]
ValueError: gziped data not streamable, pipe through zcat                              first

----------------------------------------------------------------------
Ran 102 tests in 0.925s

FAILED (SKIP=1, errors=2)
```

**Comment by kdmurray91** [comment]
This is ready for review by the way, modulo the above failure that wasn't caused by this change AFAICT.

**Comment by bocajnotnef** [comment]
Could you add a test to catch that in the future, please?

**Comment by kdmurray91** [comment]
Will do.

**Comment by kdmurray91** [comment]
@bocajnotnef after a bit of digging I've concluded I'm not sufficiently confident in the inner workings of this to write a test, and am focusing on other things for now. I'll dig deeper as time permits, otherwise maybe leave the test for others to do. Sorry mate!

**Comment by bocajnotnef** [comment]
Fair enough. I'll do a CR and merge later today.

**Comment by bocajnotnef** [comment]
Closing #27

**Comment by kdmurray91** [comment]
Thanks mate!

**Pull request merged**
