### PR TITLE
Fix release docs formatting & expand MANIFEST.in

### PR DESCRIPTION
**Pull request by mr-c**
MANIFEST.in didn't specify itself, caught by stage 3 of the release checklist.

### CODE REVIEW

**Comment by mr-c** [comment]
- [ ] Is it mergable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality, is it tested?
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  and `make doc` output. Use `make format` and manual fixing as needed.
- [ ] Is it documented in the ChangeLog?
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by mr-c** [comment]
@luizirber ready for review and merge

**Comment by luizirber** [comment]
LGTM, :+1:

**Comment by mr-c** [comment]
Thanks!

**Pull request merged**
